-- 创建temp表空间
CREATE TEMPORARY TABLESPACE win60_pdb_temp TEMPFILE '/data/oracle/oradata/orcl/win60_pdb_temp.dbf' SIZE  32m AUTOEXTEND ON NEXT  32m MAXSIZE  UNLIMITED  EXTENT MANAGEMENT LOCAL;
-- 创建数据表空间
CREATE TABLESPACE win60_pdb_data LOGGING DATAFILE '/data/oracle/oradata/orcl/win60_pdb_data.dbf' SIZE 32m AUTOEXTEND ON NEXT  32m MAXSIZE  UNLIMITED  EXTENT MANAGEMENT LOCAL;
-- 创建用户
CREATE USER WIN60DBA IDENTIFIED BY WIN60DBA ACCOUNT UNLOCK DEFAULT TABLESPACE win60_pdb_data TEMPORARY TABLESPACE win60_pdb_temp;
-- 赋权
GRANT CONNECT,RESOURCE TO WIN60DBA;
-- grant connect,resource,dba to WIN60DBA;
-- 允许用户登录
GRANT CREATE SESSION TO WIN60DBA;
-- 赋予字典表权限
GRANT SELECT ANY DICTIONARY TO WIN60DBA;
-- 赋权 tablespace win60_pdb_data
ALTER USER WIN60DBA QUOTA UNLIMITED ON win60_pdb_data;
-- 修改游标参数
ALTER SYSTEM SET open_cursors=10000;
-- 提交
COMMIT;
