FROM centos
ADD jdk-8u181-linux-x64.tar.gz /usr/local/
ADD node-v10.15.3-linux-x64.tar.xz /usr/local/
ADD gradle-5.1.1.tar.gz /usr/local/
ADD apache-maven-3.6.0-bin.tar.gz /usr/local/
CMD mkdir /opt/jenkins/
CMD mkdir /opt/jenkins_home/
ADD jenkins.war /opt/jenkins/
ENV JAVA_HOME /usr/local/jdk1.8.0_181
ENV NODE_HOME /usr/local/node-v10.15.3-linux-x64
ENV M2_HOME /usr/local/apache-maven-3.6.0
ENV GRADLE_HOME /usr/local/gradle-5.1.1
ENV JENKINS_ROOT /opt/jenkins
ENV JENKINS_HOME /opt/jenkins_home
ENV CLASSPATH $JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
ENV PATH $PATH:$JAVA_HOME/bin:$NODE_HOME/bin:$M2_HOME/bin:$GRADLE_HOME/bin
EXPOSE 8080
#CMD yum install -y git
CMD [ "/usr/sbin/init"]
CMD java -jar $JENKINS_ROOT/jenkins.war >> $JENKINS_ROOT/jenkins-run.log