USE master
GO
CREATE LOGIN WINDBA WITH PASSWORD='sql2k!@'
GO
CREATE USER WINDBA FOR LOGIN WINDBA WITH DEFAULT_SCHEMA=WINDBA
GO
ALTER SERVER ROLE [serveradmin] ADD MEMBER [WINDBA]
go
use windb
GO
CREATE USER WINDBA FOR LOGIN WINDBA WITH DEFAULT_SCHEMA=WINDBA
GO
CREATE SCHEMA WINDBA AUTHORIZATION WINDBA
GO
EXEC sp_addrolemember 'db_owner', WINDBA;
EXEC sp_addrolemember 'db_ddladmin', WINDBA;
EXEC sp_addrolemember 'db_datareader', WINDBA;
EXEC sp_addrolemember 'db_datawriter', WINDBA;

USE [windb]
GO
ALTER AUTHORIZATION ON SCHEMA::[db_datareader] TO [WINDBA]
GO
USE [windb]
GO
ALTER AUTHORIZATION ON SCHEMA::[db_datawriter] TO [WINDBA]
GO
USE [windb]
GO
ALTER AUTHORIZATION ON SCHEMA::[db_ddladmin] TO [WINDBA]
GO
USE [windb]
GO
ALTER AUTHORIZATION ON SCHEMA::[db_owner] TO [WINDBA]
GO
